export const adminModules = {
  blogs: {
    title: "Blogs",
    endpoint: "blogs",
    imageField: "image",
    fields: [
      ["title", "Blog title", "text", true],
      ["slug", "Blog slug", "text", true],
      ["short_description", "Short description", "textarea", false],
      ["full_content", "Full blog content", "textarea", false],
      ["meta_title", "Meta title", "text", false],
      ["meta_description", "Meta description", "textarea", false],
      ["status", "Status", "select", true],
    ],
    columns: ["title", "slug", "status"],
  },
  departments: {
    title: "Departments",
    endpoint: "departments",
    imageField: "image",
    fields: [
      ["name", "Department name", "text", true],
      ["slug", "Department slug", "text", true],
      ["short_description", "Short description", "textarea", false],
      ["full_content", "Full detail content", "textarea", false],
      ["facilities", "Facilities linked to department", "textarea", false],
      ["status", "Status", "select", true],
    ],
    columns: ["name", "slug", "status"],
  },
  facilities: {
    title: "Facilities",
    endpoint: "facilities",
    imageField: "image",
    fields: [
      ["title", "Facility title", "text", true],
      ["description", "Description", "textarea", false],
      ["status", "Status", "select", true],
    ],
    columns: ["title", "status"],
  },
  doctors: {
    title: "Doctors",
    endpoint: "doctors",
    imageField: "photo",
    fields: [
      ["name", "Doctor name", "text", true],
      ["designation", "Designation", "text", false],
      ["qualification", "Qualification", "text", false],
      ["specialization", "Specialization", "text", false],
      ["experience", "Experience", "text", false],
      ["department_id", "Department", "department", false],
      ["description", "Description", "textarea", false],
      ["status", "Status", "select", true],
    ],
    columns: ["name", "designation", "specialization", "status"],
  },
  gallery: {
    title: "Gallery",
    endpoint: "gallery",
    imageField: "image",
    fields: [
      ["title", "Image title", "text", false],
      ["category", "Category", "text", false],
      ["status", "Status", "select", true],
    ],
    columns: ["title", "category", "status"],
  },
  insurance: {
    title: "Insurance Partners",
    endpoint: "insurance",
    imageField: "logo",
    fields: [
      ["company_name", "Insurance company name", "text", true],
      ["description", "Description", "textarea", false],
      ["category", "Section", "insuranceCategory", true],
      ["status", "Status", "select", true],
    ],
    columns: ["company_name", "category", "status"],
  },
};
